-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 00:35:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbcadastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcadastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcadastro` DEFAULT CHARACTER SET utf8mb4 ;
USE `dbcadastro` ;

-- -----------------------------------------------------
-- Table `dbcadastro`.`estabelecimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbcadastro`.`estabelecimento` ;

CREATE TABLE IF NOT EXISTS `dbcadastro`.`estabelecimento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` INT(1) NULL DEFAULT NULL,
  `data_cadastro` DATE NOT NULL,
  `categoria` INT(1) NOT NULL,
  `razao_social` VARCHAR(50) NOT NULL,
  `nome_fantasia` VARCHAR(50) NOT NULL,
  `cnpj` VARCHAR(20) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(40) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `logradouro` VARCHAR(50) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `bairro` VARCHAR(40) NULL DEFAULT NULL,
  `cidade` VARCHAR(40) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `banco` VARCHAR(50) NULL DEFAULT NULL,
  `agencia` VARCHAR(10) NULL DEFAULT NULL,
  `conta` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
